-- ### Nerd fonts
-- DESCRIPTION:
-- Here you can edit the icons displayed in NormalNvim.

-- If you can't see the default icons:
-- Install nerd fonts and set it as your terminal font:
-- https://www.nerdfonts.com/

return {
	ActiveLSP = "",
	ActiveTS = "",
	ArrowLeft = "",
	ArrowRight = "",
	Bookmarks = "",
	BufferClose = "󰅖",
	DapBreakpoint = "",
	DapBreakpointCondition = "",
	DapBreakpointRejected = "",
	DapLogPoint = ".>",
	DapStopped = "󰁕",
	Debugger = "",
	DefaultFile = "󰈙",
	Diagnostic = "󰒡",
	DiagnosticError = "",
	DiagnosticHint = "󰌵",
	DiagnosticInfo = "󰋼",
	DiagnosticWarn = "",
	Ellipsis = "…",
	Environment = "",
	FileNew = "",
	FileModified = "",
	FileReadOnly = "",
	FoldClosed = "",
	FoldOpened = "",
	FoldSeparator = " ",
	FolderClosed = "",
	FolderEmpty = "",
	FolderOpen = "",
	Git = "󰊢",
	GitAdd = "",
	GitBranch = "",
	GitChange = "",
	GitConflict = "",
	GitDelete = "",
	GitIgnored = "◌",
	GitRenamed = "➜",
	GitSign = "▎",
	GitStaged = "✓",
	GitUnstaged = "✗",
	GitUntracked = "★",
	LSPLoaded = "",
	LSPLoading1 = "",
	LSPLoading2 = "󰀚",
	LSPLoading3 = "",
	MacroRecording = "",
	Package = "󰏖",
	Paste = "󰅌",
	Refresh = "",
	Run = "󰑮",
	Search = "",
	Selected = "❯",
	Session = "󱂬",
	Sort = "󰒺",
	Spellcheck = "󰓆",
	Tab = "󰓩",
	TabClose = "󰅙",
	Terminal = "",
	Window = "",
	WordFile = "󰈭",
	Test = "󰙨",
	Docs = "",
	Python = "",
	Replace = "󰛔",
}
